apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cno04skp1-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cno04skp1-python 
  name: cno04skp1-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cno04skp1-python 
